// Generated by scripts/generate-activity.mjs. Do not edit.
const activityKinds = <String>[
  'reasoning',
  'read',
  'write',
  'edit',
  'apply_patch',
  'search',
  'list',
  'execute',
  'fetch',
  'update_tasks',
  'subtask',
  'tool',
];
const activityStates = <String>[
  'pending',
  'running',
  'completed',
  'failed',
  'cancelled',
  'unknown',
];
